source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!
platform :ios, '11.0'

target '___PACKAGENAME___Tests' do
  test_pods
end

target 'ModuleIntegrationTests' do
	test_pods
	pod '___PACKAGENAME___', :path => './'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
