language: swift
osx_image: xcode11.1
branches:
  only:
    - master
env:
  global:
  - WORKSPACE=___PACKAGENAME___.xcworkspace
  - SCHEME=___PACKAGENAME___
  - DESTINATION='platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.1'
before_install:
  - gem install xcpretty --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration 'Debug' | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
